services:
  - type: web
    name: teloplay-web
    runtime: node
    rootDir: worker
    buildCommand: npm install
    startCommand: node worker_runner.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
